//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SellOTOP5929Entities : DbContext
    {
        public SellOTOP5929Entities()
            : base("name=SellOTOP5929Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_AddProduct> Table_AddProduct { get; set; }
        public virtual DbSet<Table_Oder> Table_Oder { get; set; }
        public virtual DbSet<Table_OderDetail> Table_OderDetail { get; set; }
        public virtual DbSet<Table_Product> Table_Product { get; set; }
        public virtual DbSet<Table_Role> Table_Role { get; set; }
        public virtual DbSet<Table_StatusAdd> Table_StatusAdd { get; set; }
        public virtual DbSet<Table_StatusBay> Table_StatusBay { get; set; }
        public virtual DbSet<Table_TilieName> Table_TilieName { get; set; }
        public virtual DbSet<Table_TypeProduct> Table_TypeProduct { get; set; }
        public virtual DbSet<Table_User> Table_User { get; set; }
        public virtual DbSet<View_AddPro> View_AddPro { get; set; }
        public virtual DbSet<View_BayOr> View_BayOr { get; set; }
        public virtual DbSet<View_Product> View_Product { get; set; }
        public virtual DbSet<View_User> View_User { get; set; }
    }
}
