//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Oder:PICPAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Oder()
        {
            this.Table_OderDetail = new HashSet<Table_OderDetail>();
        }
    
        public int O_OderID { get; set; }
        public string O_Date { get; set; }
        public string O_User { get; set; }
        public Nullable<int> O_Total { get; set; }
        public Nullable<int> O_Status { get; set; }
        public byte[] O_IMGPAY { get; set; }
    
        public virtual Table_StatusBay Table_StatusBay { get; set; }
        public virtual Table_User Table_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OderDetail> Table_OderDetail { get; set; }
    }
}
