//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_OderDetail
    {
        public int OD_OrderDetail { get; set; }
        public Nullable<int> OD_Oder { get; set; }
        public Nullable<int> OD_Amount { get; set; }
        public Nullable<int> OD_Product { get; set; }
    
        public virtual Table_Oder Table_Oder { get; set; }
        public virtual Table_Product Table_Product { get; set; }
    }
}
