//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_User:PIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_User()
        {
            this.Table_Oder = new HashSet<Table_Oder>();
        }
    
        public string U_UserName { get; set; }
        public string U_PassWord { get; set; }
        public Nullable<int> U_Tilie { get; set; }
        public string U_Name { get; set; }
        public string U_LastName { get; set; }
        public string U_HBD { get; set; }
        public string U_Phone { get; set; }
        public string U_Address { get; set; }
        public string U_Tampo { get; set; }
        public string U_Amper { get; set; }
        public string U_Province { get; set; }
        public string U_Zipcode { get; set; }
        public Nullable<int> U_Role { get; set; }
        public byte[] U_IMGUSER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Oder> Table_Oder { get; set; }
        public virtual Table_Role Table_Role { get; set; }
        public virtual Table_TilieName Table_TilieName { get; set; }
    }
}
