//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_StatusBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_StatusBay()
        {
            this.Table_Oder = new HashSet<Table_Oder>();
        }
    
        public int S_StatusID { get; set; }
        public string S_StaName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Oder> Table_Oder { get; set; }
    }
}
