//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Product:PIC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Product()
        {
            this.Table_AddProduct = new HashSet<Table_AddProduct>();
            this.Table_OderDetail = new HashSet<Table_OderDetail>();
        }
    
        public int P_ProductID { get; set; }
        public string P_ProName { get; set; }
        public Nullable<int> P_Price { get; set; }
        public byte[] P_IMG { get; set; }
        public Nullable<int> P_Amout { get; set; }
        public Nullable<int> P_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_AddProduct> Table_AddProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_OderDetail> Table_OderDetail { get; set; }
        public virtual Table_TypeProduct Table_TypeProduct { get; set; }
    }
}
