//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Product
    {
        public int P_ProductID { get; set; }
        public string P_ProName { get; set; }
        public Nullable<int> P_Price { get; set; }
        public byte[] P_IMG { get; set; }
        public Nullable<int> P_Amout { get; set; }
        public Nullable<int> P_Type { get; set; }
        public int T_TypeProID { get; set; }
        public string T_Name { get; set; }
    }
}
