//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BayOr
    {
        public int O_OderID { get; set; }
        public string O_Date { get; set; }
        public string O_User { get; set; }
        public Nullable<int> O_Total { get; set; }
        public Nullable<int> O_Status { get; set; }
        public int OD_OrderDetail { get; set; }
        public Nullable<int> OD_Oder { get; set; }
        public Nullable<int> OD_Amount { get; set; }
        public Nullable<int> OD_Product { get; set; }
        public int P_ProductID { get; set; }
        public string P_ProName { get; set; }
        public Nullable<int> P_Price { get; set; }
    }
}
