//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomeSell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_User
    {
        public string U_UserName { get; set; }
        public Nullable<int> U_Tilie { get; set; }
        public int T_TItleID { get; set; }
        public string T_TilName { get; set; }
        public string U_Name { get; set; }
        public string U_LastName { get; set; }
        public string U_HBD { get; set; }
        public string U_Phone { get; set; }
        public string U_Address { get; set; }
        public string U_Tampo { get; set; }
        public string U_Amper { get; set; }
        public string U_Province { get; set; }
        public string U_Zipcode { get; set; }
        public Nullable<int> U_Role { get; set; }
        public int R_RoleID { get; set; }
        public string R_Name { get; set; }
    }
}
